// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NZWalksCleanArch.DataService.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NZWalksCleanArch.DataService.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230930145249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NZWalksCleanArch.Entities.DbSet.Difficulty", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("82ff4bef-e4d8-4784-a45d-e09038b6b95d"),
                            AddedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9367),
                            Name = "Easy",
                            Status = 2,
                            UpdatedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9368)
                        },
                        new
                        {
                            Id = new Guid("0be7662a-6cf8-45ca-aa0e-9088d9b41ece"),
                            AddedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9380),
                            Name = "Medium",
                            Status = 2,
                            UpdatedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9381)
                        },
                        new
                        {
                            Id = new Guid("cc765ba3-3470-471f-915d-100fe14fdef0"),
                            AddedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9384),
                            Name = "Hard",
                            Status = 2,
                            UpdatedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9384)
                        });
                });

            modelBuilder.Entity("NZWalksCleanArch.Entities.DbSet.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegionImageUrl")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b082d575-2826-4277-91f5-d300ddcf3438"),
                            AddedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9465),
                            Code = "AKL",
                            Name = "AuckLand",
                            RegionImageUrl = "https://test.com/image1.png",
                            Status = 2,
                            UpdatedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9466)
                        },
                        new
                        {
                            Id = new Guid("a4f8ab81-6c1a-4935-b996-d77d822ac369"),
                            AddedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9472),
                            Code = "NTL",
                            Name = "NorthLand",
                            RegionImageUrl = "https://test.com/image2.png",
                            Status = 2,
                            UpdatedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9473)
                        },
                        new
                        {
                            Id = new Guid("84a43188-0df0-4337-a9fa-e7851cddff14"),
                            AddedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9477),
                            Code = "BOP",
                            Name = "Bay of Plenty",
                            RegionImageUrl = "https://test.com/image3.png",
                            Status = 2,
                            UpdatedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9477)
                        },
                        new
                        {
                            Id = new Guid("51440791-8a91-4e61-8f6d-602860252f93"),
                            AddedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9480),
                            Code = "WGN",
                            Name = "Wellington",
                            RegionImageUrl = "https://test.com/image4.png",
                            Status = 2,
                            UpdatedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9481)
                        },
                        new
                        {
                            Id = new Guid("390b81b6-0879-481a-8720-42f5b8637c41"),
                            AddedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9483),
                            Code = "NSN",
                            Name = "Nelson",
                            RegionImageUrl = "https://test.com/image5.png",
                            Status = 2,
                            UpdatedDate = new DateTime(2023, 9, 30, 14, 52, 49, 738, DateTimeKind.Utc).AddTicks(9484)
                        });
                });

            modelBuilder.Entity("NZWalksCleanArch.Entities.DbSet.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DifficultyId")
                        .HasColumnType("uuid");

                    b.Property<double>("LengthInKm")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WalkImageUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyId");

                    b.HasIndex("RegionId");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("NZWalksCleanArch.Entities.DbSet.Walk", b =>
                {
                    b.HasOne("NZWalksCleanArch.Entities.DbSet.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NZWalksCleanArch.Entities.DbSet.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
